### PR TITLE
Add gdrive support

### PR DESCRIPTION
**Pull request by danielfdsilva**
Todo:
- [x] Add instructions

### CODE REVIEW

**Comment by danielfdsilva** [comment]
Bad news...
This was implemented following the discussion in #40 but when I tested this I used a simple image.
Apparently it works well for small files, but when the files grow in size google enforces a confirmation:

screenshot from 2016-09-14 14 57 16

To solve this we'd probably need to download the file from google drive server side using their API. I didn't find any way to get a direct file link. This is causing more problems than what seems worth. Maybe we should look into a different hosting service?

cc @smit1678

**Comment by smit1678** [comment]
@danielfdsilva From chat, I did some digging on the google drive v2 and v3 docs: https://developers.google.com/drive/v3/reference/files/get. A url like: `https://www.googleapis.com/drive/v3/files/ [FILE ID] ?alt=media&key=[API KEY]` will work to download the larger files. 

The challenge will still be appending the API Key to the URL. We will still need to adjust the Uploader-API to make Google Drive work.

**Comment by danielfdsilva** [comment]
Uploader API changes implemented in https://github.com/hotosm/oam-uploader-api/pull/39

**Comment by smit1678** [comment]
To update here, we've added some initial instructions to how to add [via Google drive](https://docs.openaerialmap.org/uploader/uploader-form/#via-google-drive). Now this is on hold until https://github.com/hotosm/oam-uploader-api/pull/39 is merged and then deployed to production.

**Comment by smit1678** [comment]
API updates deployed on production. Merging.

**Pull request merged**
