### PR TITLE
fix help text, remove optional

### PR DESCRIPTION
**Pull request by smit1678**
Sensor property is required. This fixes the help text that says it is optional.

### CODE REVIEW

**Comment by danielfdsilva** [comment]
The validation also consider it to be optional. That has to be changed as well https://github.com/hotosm/oam-uploader/blob/fa11f92f30d6c065bf8fc6a2502c55deb8c1a696/app/assets/scripts/views/home.js#L39

**Comment by smit1678** [comment]
@danielfdsilva Ok maybe this problem is deeper than a label and validation issue. It looks like it's optional from the API side of things: https://github.com/hotosm/oam-uploader-api/blob/develop/models/upload.js#L13. 

The issue is that right now, when I leave the Sensor field blank, I get an error returned.

**Comment by danielfdsilva** [comment]
@smit1678 on the api is not optional actually. The `allow('')` makes it optional.
I think updating validation client side should be enough

**Comment by smit1678** [comment]
@danielfdsilva Ah yes, you are correct. 👍  Ok, made the addition in f509390df03ce7ccc9ae10edd3c506a1e867a829

**Pull request merged**
