### PR TITLE
Feature/direct uploads

### PR DESCRIPTION
**Pull request by danielfdsilva**

### CODE REVIEW

**Comment by nbumbarger** [comment]
@danielfdsilva The direct upload feature is ready for review. It connects with the API changes in [this PR](https://github.com/hotosm/oam-uploader-api/pull/53) (I am about to address your API change request, but the functionality will not change). As always, testing this will require the [API](https://github.com/hotosm/oam-uploader-api/tree/feature/direct-uploads) and the [oam-uploader-admin](https://github.com/hotosm/oam-uploader-admin) page to be running, as per [these instructions](https://github.com/hotosm/oam-docs/pull/36/files).

**Comment by danielfdsilva** [comment]
- Handle progress bar in case of failure
- Change "upload" to "local file"

**Review by smit1678 — APPROVED** [review]
Looks good

**Comment by nbumbarger** [comment]
This should be merged after the [API changes](https://github.com/hotosm/oam-uploader-api/pull/53) that enable uploads.

**Comment by smit1678** [comment]
@nbumbarger @danielfdsilva Regarding the license field before we merge. I don't think we want this as a free form text, especially for production OAM. We'll still only be using CC-BY 4.0 at the moment, so we may want to implement a pre-filled radio button as well as reposition the license text that is at the bottom of the page.

**Comment by smit1678** [comment]
@nbumbarger Coming back here now that we've tested a bit. I think the final thing here is: 

- [ ] license input. Unless you have other ideas, I think we implement a single radio button for CC-BY 4.0. This shouldn't be free form text. Since main OAM will only require CC-BY 4.0, other implementations of this, like PacDID, could leverage other licenses and this gives flexibility. 
- [ ] changes on the Uploader API to move `license` and `tags` into the `properties` objects.

**Comment by nbumbarger** [comment]
@smit1678 for the license input, do you mean a boolean checkbox for imagery with/ without the CC-BY 4.0 license?

**Comment by smit1678** [comment]
@nbumbarger I don't think we want to do a check box to enable other implementations of this to add different licenses.

**Comment by nbumbarger** [comment]
Closing in favor of https://github.com/hotosm/oam-uploader/pull/65, which updates the site for compatibility with the tiler backend.

**Pull request closed without merging**
